---
title: "03_clustering"
author: "JR"
date: "8/15/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
library(tidyverse)
library(GenomicRanges)
library(ggplot2)
library(pheatmap)
library(ComplexHeatmap)
source("../../util/my_class_functions.R")
source("../../util/_setup.R")
install.packages("colorRamps")

```

# loading in peak_features env objects from 01_create_consensus_peaks
```{r laod env objects}

load("../01_create_consensus_peaks/results/peak_features.RData", verbose = T)

```

# creating distance matrix & dendrogram
```{r distance matrix and dendrogram}

# creating distance matrix
peak_occurence_dist <- dist(promoter_peak_matrix, method = "binary")

# clustering distance values
bin_hier <- hclust(peak_occurence_dist, method = "complete")

# heat map
ggdendro::ggdendrogram(bin_hier, rotate = FALSE,  size = 3,
                       theme_dendro = TRUE) +
   # 90 degree rotation to right
   coord_flip() +
   scale_y_continuous() +
   # adds label
   scale_x_continuous(position = "top") +
   # subsection to labels in order of clustering
   # ? seq_along
   scale_x_continuous(breaks = seq_along(bin_hier$labels[bin_hier$order]),
                      # adding labels that are in the order 'column'
             labels = bin_hier$labels[bin_hier$order], position = "top",
             expand = c(0,0)) +
   theme(axis.text.x = element_text(angle = 90, hjust  = 1)) +
   theme(axis.text.y = element_text(angle = 0,hjust = 1)) +
   scale_y_reverse(expand = c(0.01, 0)) +
   theme(
     plot.background = element_blank(),
     panel.grid.major = element_blank(),
   panel.grid.minor = element_blank(),
     panel.border = element_blank()
   )

```

# clustered heatmap of binding similarity

```{r heatmap of binding similarities}

# pdf("figures/binding_similariy_heatmpa.pdf", height = 12, width = 70)
# pheatmap(promoter_peak_occurrence_matrix, show_colnames = FALSE, clustering_distance_rows = "binary", clustering_distance_cols = "binary")
# dev.off()


# pheatmap(promoter_peak_occurrence_matrix, show_colnames = FALSE, clustering_distance_rows = "binary", clustering_distance_cols = "binary")
# dev.off()




```


# start point for metaplots and clustering
```{r}
load("../../../05_R_analyses/01_peak_features/results/peak_features.RData", verbose = T)
```



```{r}

metaplot_df <- data.frame(x = integer(), dens = numeric(), dbp = character())
# Writting a for loop to calculate promoter coverage for all consensus_peaks:
for(i in 1:length(filtered_consensus_list)) {
  print(names(filtered_consensus_list)[[i]])
  tmp_df <- profile_tss(filtered_consensus_list[[i]], lncrna_mrna_promoters)
  tmp_df$dbp <- names(filtered_consensus_list)[[i]]
  metaplot_df <- bind_rows(metaplot_df, tmp_df)
  
}
# write_rds(metaplot_df, "metaplot_df.rds")
write_rds(metaplot_df, "results/metaplot_df_final.rds")

```
  


```{r}


metaplot_filtered_matrix <- metaplot_df %>% 
  pivot_wider(names_from = x, values_from = dens) %>%
  column_to_rownames("dbp") %>%
  as.matrix()
# Let's see how many have NA values
table(rowSums(is.na(metaplot_filtered_matrix)))
# If there are any NAs Let's filter out those is.na
# metaplot_filtered_matrix <- metaplot_filtered_matrix[rowSums(is.na(metaplot_filtered_matrix)) == 0,]
# Z-Scale the rows for clustering (not needed for profile plots)
mm_scaled <- t(scale(t(metaplot_filtered_matrix)))
# clustering
metaplot_hclust <- hclust(dist(mm_scaled), method = "complete")
# plotting
plot(metaplot_hclust)
# Plot the dendrogram
pdf("figures/tss_profile_dendrogram.pdf", height = 10, width = 27)
par(cex=0.3)
plot(metaplot_hclust)
dev.off()
```


```{r}
col_fun <- colorRamp2(c(-3, 0, 3), c("#5980B3", "#ffffff", "#B9605D"))
split <- data.frame(split = c(rep("-1kb",1000), rep("+1kb", 1000)))
# pdf("figures/tss_profile_heatmap.pdf", height = 35, width = 10)
Heatmap(mm_scaled, cluster_columns = FALSE, col = col_fun, border = TRUE, 
        show_column_names = FALSE,
        use_raster = TRUE,
        column_split = split,
        column_gap = unit(0, "mm"),row_names_gp = gpar(fontsize = 7))

pdf("figures/tss_profile_heat_map.pdf", height = 10, width = 27)

Heatmap(mm_scaled, cluster_columns = FALSE, col = col_fun, border = TRUE, 
        show_column_names = FALSE,
        use_raster = TRUE,
        column_split = split,
        column_gap = unit(0, "mm"),row_names_gp = gpar(fontsize = 7))
dev.off
#TODO how to save?
ggsave("figures/tss_profile_heat_map.pdf")
ggsave("figures/meta_heatmap.pdf", height = 50, width = 12, limitsize = F)

par(cex=0.3)
dev.off()

# dev.off()
# # Now a heatmap with only cluster 1 since it has the most dbps (3).
# Heatmap(mm_scaled[clusters == 1,], cluster_columns = FALSE, col = col_fun, border = TRUE, 
#         show_column_names = FALSE,
#         use_raster = TRUE,
#         column_split = split,
#         column_gap = unit(0, "mm"),row_names_gp = gpar(fontsize = 7))
# par(cex = 1)


pdf("figures/tss_profile_heatmap.pdf", height = 35, width = 10)
Heatmap(mm_scaled, cluster_columns = FALSE, col = col_fun, border = TRUE, 
        show_column_names = FALSE,
        use_raster = TRUE,
        column_split = split,
        column_gap = unit(0, "mm"),row_names_gp = gpar(fontsize = 7))
dev.off()
```


```{r}


```


