---
title: "Getting_git"
author: "JR"
date: "7/18/2022"
output: html_document
---

Our first objective today will be to sync to the class github. We will
go over a few needed things to establish git connections:

### Sign up for github -- if you have already have nothing to do.


## FIRST STEP: set up ssh connection to github (one time only)
Navigate to your home directory on fiji ~/IDENTIKEY

```{bash}

cd ~
ls -lah

```

Note that there is a .ssh folder that you can place these unique keys to let
servers communicate securely. We can check to see if a key already exists.
If it doesn't we will generate one with the with ssh-keygen command.

Here we are connecting out "public key" on our server "Fiji" to github.
# If you want to connect your local computer there is also a .ssh file (MAC)

```{bash}
cd ~/
cd .ssh
ls -lah

# If it exists already, you can check out the public key using cat
cat id_rsa.pub

```


# Making a new RSA keygen if you don't already have one
```{bash}

ssh-keygen -t rsa
# just use the default name and no password needed
# Then cat the contents of the public key file (id_rsa.pub) and copy to clipboard.


# In windows you can use puttygen to create the key  
# Mac or Linux you can use ssh-keygen
# The instructions for creating a key with putty are here and detailed.
# https://www.ssh.com/ssh/putty/windows/puttygen


```

Now let's got to your github website. 
You will need to sign into your github account first.

On the top right there is a drop down menu. 
Click on "Settings". Now you will see on the left side there is a list of options. 
Click on "SSH and GPG Keys" > "Add new key" on top right (green button). Paste in the new public SSH key we just generated.

# You may also want to go to your local computer shell .ssh folder (same place).
Generate a key and paste into github as done above. This way your local terminal
(not fiji server) can push to github too. Basically any machine(s) you want to
talk to github need this "handshake" SSH key.

Cool we are all connected !


# Setting up direct acess to fiji (no password needed anymore!)
```{BASH}

# We will be adding the public key to the `~/.ssh/authorized_keys` file on FIJI.
# Then as above for github, you'll copy the public key to your clipboard
# and paste it into `~/.ssh/authorized_keys` on FIJI

nano ~/.ssh/authorized_keys
# Then paste in the key and save file.
# ctrl x, y to exit nano and save

# This will allow you to log-in to fiji without having to type your
# password in each time.


ssh identikey@fiji.colorado.edu 
# should connect directly with out a password 
```


--------- Nice we are all connected --------------



# {VERSION ONE cloning: start on your git hub site} 
Now let's clone the class git hub

# STEP 1: GO TO YOUR GIT HUB and make new repository called: CLASS_2023
You can leave empty

# STEP 2: clone in directory of choosing   
```{git bash}

# navigate to the directory of your choosing locally 
# On fiji
cd /scratch/Shares/rinnclass/CLASS_2023/<YOUR_NAME>

# NOW Clone via termial
git clone git@github.com:boulderrinnlab/CLASS_2023.git

# Cool so you can see all the class files now !!
# change directories into the new folder that was cloned
cd CLASS_2023/

```

# STEP 3 : initialize
```{git bash}

# simply type:
git init

# ok one step closer
```


# STEP 4: set up remote origin and url
```{git bash}

# setting up git origin
git remote add origin git@github.com:your_github/CLASS_2023.git
# git remote add origin git@github.com:rinntestsite/CLASS_2023.git

# setting up origin
git remote set-url origin git@github.com:YOU/REPO_NAME.git
# git remote set-url origin git@github.com:rinntestsite/CLASS_2023.git


```

# STEP 6: git push to upstream origin master
```{git }

# type this in 
git push --set-upstream origin master


# now go back to your git hub website and you should see all the files there !

```


# STEP 7: make a new file and push

```{git bash}

# make a new .Rmd
nano test.Rmd
# type in whatever you want and cntrl-x, y, enter to exit

# check on git status
git status

# now add the .rmd
git add test.Rmd

# now commit
git commit -m "adding first file"

# now push 
git push

# check on your git hub site and should have new .Rmd file !

```

# Now let's make sure you are configured with the right email
Did you see a green square show up on your git site to credit the commit?
If not you probably have an email that is not the same as your git site

```{git bash}

# let's see what our git configuration is:
cat ~/.gitconfig

# or we can see everything with this:
git config --list

# is your email the same as the one you set up git hub?
# If not we can easily change:

# Set your username:
git config --global user.name "FIRST_NAME LAST_NAME"

# Set your email address  **** this should be the same as the one associated with your git hub *****
git config --global user.email "MY_NAME@example.com"

# note you can remove the origin and change above 
git remote rm origin
```

Ok that was a lot but now you have the class cloned and can make changes and commit to your own git hub site !!


# ANOTHER APPROACH: FORKING

On your git hub site search for "boulderrinnlab"
Click on CLASS 2023 recent commits

On the top right you will see "FORK"
Click that and you will have everything ready to go !

# Now clone this using the terminal
Create a new file (nano test.Rmd) -- type something and save
git add test.Rmd
git commit -m "let's hope this pushes"
git push

Check on your git hub site and you should see test.Rmd after refreshing

This seems much easier and is a more "social" way to clone as it will be noted by creator of repo 

