---
title: "01_create_consensus_peaks"
author: "JR"
date: "8/10/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)
library(tidyverse)
library(GenomicRanges)
source("../../util/my_class_functions.R")

# filepath to import peaks
basepath <- "/scratch/Shares/rinnclass/CLASS_2023/<your_folder>"
peak_path <- "CLASS_2023/CLASSES/05_R_analyses/analysis/00_consensus_peaks"
broadpeakfilepath <- "/scratch/Shares/rinnclass/CLASS_2023/data/data/peaks"
```

# Loading in all .broadPeak files for all dbps and their replicates

```{r load .broadPeak files}

# using import peaks to import .broadPeak files (~10min)
peak_list <- import_peaks(consensus_file_path = broadpeakfilepath)

```

# creating consensus peaks
Using consensus_from_reduced function that requires peak list
and dbp object. This will be done in 2 steps
(1) created dbp object of unique names for dbp
(2) run consensus_from_reduced


```{r create consensus peaks}

  # Creating unique DBP object for create_consensus_peaks_from_reduced
dbp <- unique(sapply(names(peak_list), function(x) {
   unlist(strsplit(x, "_"))[1]
}))

# now run our function consensus_from_reduced
consensus_list <- lapply(dbp, consensus_from_reduced, peak_list)

# adding names to the GRange list
names(consensus_list) <- dbp

# exporting consensus peaks into results
 for(i in 1:length(consensus_list)) {
  rtracklayer::export(consensus_list[[i]], 
                     paste0("results/consensus_peaks/", 
                            names(consensus_list)[i], 
                            "_consensus_peaks.bed"))
 }

```


```{r}

dbp <- unique(sapply(names(peak_list[1]), function(x) {
   unlist(strsplit(x, "_"))[1]
}))



  dbp_peaks <- peak_list[grepl(as.character(dbp), names(peak_list))]
  suppressWarnings(all_peaks <- GenomicRanges::reduce(unlist(as(dbp_peaks, "GRangesList"))))
  all_peaks <- all_peaks[grepl("chr", seqnames(all_peaks))]
  peak_exists <- matrix(NA, nrow = length(all_peaks), ncol = length(dbp_peaks))
  for(i in 1:length(dbp_peaks)) {
    suppressWarnings(peak_exists[,i] <- as.numeric(countOverlaps(all_peaks, dbp_peaks[[i]]) > 0))
  
all_peaks_df <- all_peaks %>% as.data.frame
unique(all_peaks_df$seqnames)
```

